# Generated by Django 3.2.5 on 2021-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('desc', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
